// <auto-generated />
using System;
using WeatherApp.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WeatherApp.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408175554_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeatherApp.Api.Domain.WeatherForecast.WeatherForecastReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Lat")
                        .HasPrecision(9, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("Lon")
                        .HasPrecision(9, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("WeatherCode")
                        .HasColumnType("integer");

                    b.Property<double>("WindSpeed")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("weather_forecast_readings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
